{
  imports = [
    ./anyrun
    ./fastfetch
    ./hyprland
    ./ironbar
    ./nvim
    ./quickshell
    ./rofi
    ./walker
    ./zen-browser
    ./dbus.nix
    ./dunst.nix
    ./easyeffects.nix
    ./ghostty.nix
    ./gnome-keyring.nix
    ./greetd.nix
    ./hypridle.nix
    ./hyprlock.nix
    ./hyprpaper.nix
    ./kitty.nix
    ./okular.nix
    ./syncthing.nix
    ./udiskie.nix
    ./yazi.nix
  ];
}
